package io.github.mobilebytelabs.supabaseauth.convention

import kotlinx.kover.gradle.plugin.dsl.KoverProjectExtension
import org.gradle.api.Project

/**
 * Configures the `kover` plugin with the [configure] lambda.
 *
 * Mirrors [configureDokka] so KoverConventionPlugin reads the same way as
 * DokkaConventionPlugin.
 */
internal inline fun Project.koverGradle(crossinline configure: KoverProjectExtension.() -> Unit) =
    extensions.configure(KoverProjectExtension::class.java) {
        configure()
    }

/**
 * Root-level kover report configuration — the single source of truth for the filter and verify
 * rules that gate the aggregated coverage report.
 *
 * Applied by `KoverConventionPlugin` when it runs on the root project. Coverage is aggregated
 * at the root rather than measured per module: a per-module report for a library split across
 * 23 `auth-*` modules tells you nothing about the toolkit's overall coverage, and Kover's own
 * multi-module KMP guide recommends root aggregation.
 * https://kotlin.github.io/kotlinx-kover/gradle-plugin/#multi-module-kotlin-multiplatform-project
 *
 * Tasks: `./gradlew koverHtmlReport | koverXmlReport | koverVerify`
 */
internal fun Project.configureKoverRootReports() = koverGradle {
    reports {
        filters {
            excludes {
                classes(
                    "*.di.*", // Koin DI modules — wiring, not logic
                    "*.BuildConfig",
                    "*ComposableSingletons*", // Compose-generated lambda holders
                    "*_*Factory*", // Generated factories
                    "*\$ComposableLambda\$*",
                    "*Preview*", // @Preview functions
                    "*Test*", // test helpers themselves
                    // Generated by cmp-observe-metadata.gradle.kts for every auth-* module.
                    "*.CmpMetadata",
                )
                packages(
                    "*.generated.*",
                    "*.ksp.*",
                )
                annotatedBy(
                    // @Composable functions are verified by Compose UI tests and screenshot
                    // tests, not line coverage — counting them distorts the number in both
                    // directions.
                    "androidx.compose.runtime.Composable",
                )
            }
        }
        verify {
            // The default here is 0 only as a fallback for a consumer that sets no property;
            // this repo pins `koverLineMin=30` in gradle.properties, just under the 32.67%
            // measured on 2026-09-27. A 0 floor makes `koverVerify` incapable of failing, so
            // treat an unset property as a configuration bug rather than a valid state.
            rule {
                minBound((project.findProperty("koverLineMin") as? String)?.toIntOrNull() ?: 0)
            }
        }
    }
}
