blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/MobileByteLabs/kmp-supabase-auth#readme
    about: Please read the documentation before opening an issue
  - name: Discussions
    url: https://github.com/MobileByteLabs/kmp-supabase-auth/discussions
    about: Ask questions and discuss ideas
